/* Generated by ts-generator ver. 0.0.8 */
/* tslint:disable */

import { Contract, ContractTransaction, EventFilter } from "ethers";
import { Provider } from "ethers/providers";
import { BigNumber } from "ethers/utils";
import { TransactionOverrides } from ".";

export class IMetaERC20Wrapper extends Contract {
  functions: {
    deposit(
      _token: string,
      _value: number | string | BigNumber,
      overrides?: TransactionOverrides
    ): Promise<ContractTransaction>;

    withdraw(
      _token: string,
      _to: string,
      _value: number | string | BigNumber,
      overrides?: TransactionOverrides
    ): Promise<ContractTransaction>;
  };
  filters: {};
}
